OPENAI_API_KEY=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
QDRANT_CLOUD_URL="https://dfa74afb-21f2-454e-9314-c4df231a3822.europe-west3-0.gcp.cloud.qdrant.io:6333",
QDRANT_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.iiY8YYaVdcDEr5BAktATJgxWImqVZ1fY_AnWfNQ88UM",
